/*
	Manisha Macharla
*/

package com.book.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
//The @Entity annotation is placed before the class declaration to specify that the Admin class is an entity in the
//JPA context. It maps to a database table for storing administrative user information.
@Entity
public class Admin {
	//The @Id annotation is used to indicate that the id field is the primary key of the entity. 
	//It uniquely identifies each record in the database table.
    @Id
    //The @GeneratedValue annotation, with the GenerationType.IDENTITY strategy, specifies that the primary key values for
    //new Admin records are generated by the database. The strategy is set to auto-increment the id values, making them
    //    unique.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String username;
    private String password;

    // Constructors

    public Admin(int id, String username, String password) {
        super();
        this.id = id;
        this.username = username;
        this.password = password;
    }

    public Admin() {
        super();
    }

    // Getters and Setters

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    // toString() Method

    @Override
    public String toString() {
        return "Admin [id=" + id + ", username=" + username + ", password=" + password + "]";
    }
}
